version: "3.5"
services:
    monitor:
        build: docker
        ports:
            - 5000:5000
        depends_on:
            - mongodb
        volumes:
            - ./src:/monitor
        command: python /monitor/monitor.py
        env_file: docker/environment
        labels:
            - amf=2020
    mongodb:
        image: mongo
        labels:
            - amf=2021
