version: "3.5"
services:
    monitor:
        build: .
        ports:
            - 5000:5000
        depends_on:
            - mongodb
        volumes:
            - ./config/monitor.yml:/monitor/config/monitor.yml
        command: python monitor.py --config config/monitor.yml
    mongodb:
        image: mongo
